### ISSUE TITLE
Makefile does not respect CFLAGS/LDFLAGS flags

### ISSUE THREAD

**Issue by blshkv** [ufrisk/LeechCore#1]
```
 * QA Notice: Files built without respecting CFLAGS have been detected
 *  Please include the following list of files in your report:
 * /usr/lib64/leechcore.so


 * QA Notice: Files built without respecting LDFLAGS have been detected
 *  Please include the following list of files in your report:
 * /usr/lib64/leechcore.so
```

Let me know if you need more details.

**Comment by blshkv** [comment]
The bug is NOT fixed. Why did you closed my report?

**Comment by ufrisk** [comment]
Apologies, but I've double checked the Makefile and I don't even use any special LDFLAGS in it. Also it builds really nicely without any errors for me on the distros I've tested - and the resulting library works fine. I just don't see the error. I'm a Makefile noobie tho.

If you believe I still have a bug in the Makefile I'd be more than happy to accept a PR to remedy the issue though :)

**Comment by blshkv** [comment]
can you copy a solution from any other bug report, like this one:
https://github.com/ntop/PF_RING/pull/507#pullrequestreview-280113969

**Comment by ufrisk** [comment]
so if I understand this correctly changing `CFLAGS=` into `CFLAGS+=` and also adding a new separate line `LDFLAGS   += -g -shared` will fix the warnings?

**Comment by blshkv** [comment]
Yes, should be it. I will try to test it in a bit

**Comment by ufrisk** [comment]
I hope this should be fixed now.

**Comment by blshkv** [comment]
Tested with 1.5, the issue is NOT fixed, sorry:
```
 * QA Notice: Files built without respecting LDFLAGS have been detected
 *  Please include the following list of files in your report:
 * /usr/lib64/leechcore.so

```

**Comment by ufrisk** [comment]
I hope this issue should finally be fixed this time.

**Comment by blshkv** [comment]
Hi, it is fixed indeed. Cheers!
