### ISSUE TITLE
build failed python.h missing

### ISSUE THREAD

**Issue by johnjohnsp1** [ufrisk/LeechCore#10]
hello, i'm trying to compile this from source but sadly even if following the steps:

Dependencies:

    Python: download Windows x86-64 embeddable zip file from python.org and unzip its contents in the LeechAgent\Python sub-folder.
    WinPMem: download the signed 64-bit driver from Github and place it in the LeechAgent folder alongside leechagent.exe.

i get this :

C:\temp\leechcore\leechcorepyc\leechcorepyc.c(12,10): fatal error C1083: Cannot open include file: 'python.h': No such
file or directory [C:\temp\leechcore\leechcorepyc\leechcorepyc.vcxproj]
  leechcorepyemb.c
C:\temp\leechcore\leechcorepyc\leechcorepyemb.c(15,10): fatal error C1083: Cannot open include file: 'python.h': No suc
h file or directory [C:\temp\leechcore\leechcorepyc\leechcorepyc.vcxproj]

using command line with this syntax:
C:\temp\leechcore>msbuild LeechCore.sln -t:Build -p:Configuration=Release

anyone else get this same error ?
thanks

**Comment by ufrisk** [comment]
The instructions about Python is more for using it from a pre-compiled binary standpoint.

You'll have to alter the `leechcorepyc.vcxproj` file manually, alternatively install the Visual Studio bundled Python 3.7 to build due to this line:

https://github.com/ufrisk/LeechCore/blob/b1f6047dec48a3258d31cde00f68be73630737a5/leechcorepyc/leechcorepyc.vcxproj#L56

**Comment by johnjohnsp1** [comment]
thanks for the fast reply i will try fix manually as you pointed me out. Any chance to successfully compile on a VStudio 2017 ? thanks once more

**Comment by ufrisk** [comment]
I believe things will be fine with VS2017 as well (almost 100% certain); but it's not something I would support if things aren't working.

**Comment by johnjohnsp1** [comment]
appreciate for the help so far and i really say thanks for release this kind of tool thats a great work !!
