### ISSUE TITLE
Writing causes the gateware to lock up on Linux

### ISSUE THREAD

**Issue by ko1N** [ufrisk/LeechCore#19]
Using LeechCore to write memory causes issues on Linux.

I implemented some custom code to read/write a target via the FPGA using LeechCore (using LcReadScatter / LcWriteScatter).

I noticed that when "heavily pressuring" the FPGA (just reading a lot of things and occasionally writing a few smaller values without any sleeps/timeouts) that after a few writes every subsequent call to either Read/Write memory fails (they just return 0 and fail).
Even reloading LeechCore will not fix this issue. The FPGA stays locked until I power cycle it.

I could only observe this behavior on Linux when writing memory. When I was just reading memory this issue never occurred.

Another interesting thing I observed was that this only happens on Linux. The same code worked flawlessly (reading + writing) on Windows. Also, both the ft60x driver and libusb implementation show the exact same issue.

Maybe it could be related to sending the buffers to the FPGA as reading was totally fine?

Best regards,
Patrick

**Comment by ufrisk** [comment]
Thank you for reporting this issue. This may be somewhat tricky to look into but I'll get to it eventually. I have a few other things planned that are taking up the majority of my time right now. I'll however try to look into it at the end of the year (end of December) unfortunately.

**Comment by ko1N** [comment]
I wasn't able to reproduce the issue anymore so we might just close thanks. Thanks for taking your time though! :+1:
