### ISSUE TITLE
Error appears after few seconds of Leech initializing

### ISSUE THREAD

**Issue by aDioS786** [ufrisk/LeechCore#20]
Hi,
New to this, using Leechcore. Currently it randomly starts working for me, whereas quite often it just stops after a second or two on initializing 
I don't see any errors in console, whereas if I go in event viewer I do get below errors:

Faulting application name: notepad.exe, version: xxxxxx, time stamp: xxxhexxxx
Faulting module name: leechcore.dll, version: 2.1.5.18, time stamp: 0xHexxxx

When this occurs, screamer stops working, and only way to get it back to live is to restart. Any idea?

Thanks

**Comment by ufrisk** [comment]
Hi,

1) Are you using the ScreamerM2 or the PCIeScreamer?
2) I don't recognize the syntax; also leechcore isn't able to read processes such as notepad by itself...
2.1) which language are you using?
2.2) which API are you calling into; the LeechCore directly (not possible to specify notepad like that); or the MemProcFS or some other layer ontop of leechcore. If so, which API layer is that?

It looks very much like some crash inside the leechcore though; but I would need the above info requested to start with together with a copy of the error message in event viewer including the error code.

**Comment by aDioS786** [comment]
Hi,
Yes using ScreamerM2. 
Yeh sorry, it was my own class i was messing with, so I am initializing using reuqired parameters i.e. -v, -device, fpga as in one of ur examples in vmm_example.cs,  vmm.PidGetFromName, and then accessing the memory it.

I am using c#

**Comment by ufrisk** [comment]
what does the windows event say? message and error code?

**Comment by aDioS786** [comment]
Same as above 
Faulting module name: leechcore.dll, version: 2.1.5.18, time stamp: 0x5f72a4d9

**Comment by ufrisk** [comment]
Thanks, Does this error stay the same if you use the most recent binary distribution of the MemProcFS downloaded from here: https://github.com/ufrisk/MemProcFS/releases/tag/v3.6

I updated the LeechCore some time ago to fix some issues. I suspect this is another issue; but it would be good to know if upgrading to the latest version fixes this before looking into this.

**Comment by aDioS786** [comment]
odd ur code isn't running, ExampleVmm > for some reason not loading the vmm.dll, although it is in output folder i.e. bin\Debug...
(output path was: files\temp\vmmsharp). Even reverting back to what it was, still not loading it.
Unable to load vmm.dll
bool fResult = vmmi.VMMDLL_InitializeEx(args.Length, args, out pLcErrorInfo)

**Comment by ufrisk** [comment]
Are you running c# in 64-bit mode? also are you using the latest vmmsharp.cs as well? I changed some function names around so you would need the latest one.

**Comment by aDioS786** [comment]
Yes running in X64, I have re-downloaded the whole source from link above v3.6 which is ur latest code for it. Please correct if I am getting confused somewhere

**Comment by ufrisk** [comment]
on a fresh install visual studio 2019 I did:

`git clone https://github.com/ufrisk/MemProcFS`
`git clone https://github.com/ufrisk/LeechCore`

then open MemProcFS.sln

set the vmmsharp project as default

rebuild solution

and then it seems I needed to do another rebuild on vmmsharp project separately to avoid some error

then it worked...

make sure latest leechcore project is alongside memprocfs project as it's referenced by the memprocfs project.

**Comment by aDioS786** [comment]
Thanks, yeh I changed path, re-cloned repo and build vmm and leechcore. Now getting read or write protected memory.
What best way would you recommend to do, to open and read specified process.

**Comment by ufrisk** [comment]
there is probably an issue then; can you replicate the issue and post the code here in the shortest possible lines of code so that I can look into it?

i.e. something like this

```C#
vmm.Initialize("-printf", "-v", "-device", "c:\\dumps\\WIN7-X64-SP1-1.pmem");
uint dwExplorerPID;
vmm.PidGetFromName("explorer.exe", out dwExplorerPID);
vmm.MAP_MODULEENTRY mModuleKernel32 = vmm.Map_GetModuleFromName(dwExplorerPID, "kernel32.dll");
byte[] dataKernel32MZ = vmm.MemRead(dwExplorerPID, mModuleKernel32.vaBase, 128, 0);
```

just the shortest possible amount of code to reliably trigger the issue if that's possible. If it's happening completely at random that would be good to know as well; but from your issues I suspect it's happening all the time.

**Comment by ufrisk** [comment]
I'm closing this issue due to old age. I'm assuming/hoping it has been resolved. If not please let me know.
