### ISSUE TITLE
Performance regression on linux due to thread suspend in usleep()

### ISSUE THREAD

**Issue by ko1N** [ufrisk/LeechCore#21]
On Windows LeechCore is using a custom usleep function which does not cause a thread suspend.
On Linux the regular usleep() function is used which causes a thread suspend and doesn't guarantee to return instantly after the amount of time has passed.

Edit: after further testing the performance improvement seemed to be just a few % but still valuable :+1:

**Comment by ufrisk** [comment]
I'm closing this issue due to old age. usleep() is working well enough I think.

Also, 100% performance gain have been recently been achieved by adding additional usleep()'s (together with futex+thread).
