### ISSUE TITLE
What software should I install to read memory

### ISSUE THREAD

**Issue by bbhxwl** [ufrisk/LeechCore#23]
I am a beginner, DMA has been confirmed installed, computer a motherboard installed DMA, and then USB connection to computer B, I should install in computer B what software, can read memory?

**Comment by ufrisk** [comment]
I'm really sorry about the super slow response. I must have missed this issue somehow and for that I apologize.

I assume you got it to work somehow since it was quite a few months since last and I'm closing the issue. Please let me know otherwise and I'll answer much faster.

**Comment by bbhxwl** [comment]
> I'm really sorry about the super slow response. I must have missed this issue somehow and for that I apologize.
> 
> I assume you got it to work somehow since it was quite a few months since last and I'm closing the issue. Please let me know otherwise and I'll answer much faster.

I haven't studied how to use it yet. I want to use c# call.

**Comment by ufrisk** [comment]
You should include the vmmsharp.cs wrapper in your project. The wrapper and also example code is found in the vmmsharp project. https://github.com/ufrisk/MemProcFS/tree/master/vmmsharp
