### ISSUE TITLE
Does this application run on vmware virtual computer ?

### ISSUE THREAD

**Issue by maskelihileci** [ufrisk/LeechCore#24]
If it works, can there be a video about the installation?

**Comment by ufrisk** [comment]
1) It depends on what you mean with "does this application run on vmware virtual computer". Most parts will work yes. But if you're thinking about doing DMA the USB connection towards the attack device is problematic (even though I don't think it would be impossible).

2) Installation videos: this is an excellent suggestion. It's something I'll definitely look into. Right now I'm a but busy rewriting the memory analysis library in my MemProcFS project to bring it to python pip. But after that I might look into making some videos about installation and usage.
