### ISSUE TITLE
C# API Attempted to read or write protected memory

### ISSUE THREAD

**Issue by MystifiedSky** [ufrisk/LeechCore#31]
No matter what I do I get attempted to write protected memory.  I have allow unsafe code to run other then that and setting cpu to x64 everything is default and console application c#.  First I was just trying to run the c# examples and breakpoint through to get a idea of what everything was doing but that gave the memory issues too.  Then I took this snipped of code from another issue since it was simple and having the same issue.

The code is as follows.

```
using System;
using System.Runtime.InteropServices;
using vmmsharp;

namespace CSharpApex1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            // initialize vmm with verbose mode with fpga device
            Vmm vmm = new Vmm("-printf", "-v", "-device", "fpga");
            uint dwExplorerPID;
            vmm.PidGetFromName("explorer.exe", out dwExplorerPID);
            Vmm.MAP_MODULEENTRY mModuleKernel32 = vmm.Map_GetModuleFromName(dwExplorerPID, "kernel32.dll");
            byte[] dataKernel32MZ = vmm.MemRead(dwExplorerPID, mModuleKernel32.vaBase, 128, 0);
        }
    }
}
```
![Screenshot_43](https://user-images.githubusercontent.com/47060964/195867883-15142a60-cf22-4a0e-9b77-557e03a01f24.png)

The Error
![Screenshot_42](https://user-images.githubusercontent.com/47060964/195867682-1c733a21-400b-4bcf-9a2a-fc2c96cf66e1.png)

**Comment by ufrisk** [comment]
Are you always getting this error when calling into the PidGetFromName() function?

If you do a physical memory dump of the system to a file are you able to replicate the issue and get the same result?

**Comment by MystifiedSky** [comment]
> Are you always getting this error when calling into the PidGetFromName() function?
> 
> If you do a physical memory dump of the system to a file are you able to replicate the issue and get the same result?

I get it with the ConfigGet() function too this is just running through with a breakpoint of the c# example.   I am by far a noob when it comes to this but am trying to learn something new :).  To give a little more info I have a Squierrel with custom firmware (could that be the issue?)
![Screenshot_1](https://user-images.githubusercontent.com/47060964/195882511-86efb2e7-4c58-413d-ae5d-38636e387f2b.png)
![Screenshot_2](https://user-images.githubusercontent.com/47060964/195882520-2a4902ff-e6bd-455c-b672-9d39b0dfd1c7.png)

**Comment by ufrisk** [comment]
Having different firmware on your PCIe device should not cause issues like this.

If you do a memory dump with PCILeech (alternatively copy the file M:\memory.pmem if you use my memprocfs program and then try to use the dump file in your C# program. Does it cause the same issue?

**Comment by MystifiedSky** [comment]
> Having different firmware on your PCIe device should not cause issues like this.
> 
> If you do a memory dump with PCILeech (alternatively copy the file M:\memory.pmem if you use my memprocfs program and then try to use the dump file in your C# program. Does it cause the same issue?

Sorry for delay I took a nap I do get this while running your memprocFS program.
![Screenshot_5](https://user-images.githubusercontent.com/47060964/195920381-dbb79ecf-025d-4777-83f2-260a8590da3c.png)

**Comment by MystifiedSky** [comment]
> Having different firmware on your PCIe device should not cause issues like this.
> 
> If you do a memory dump with PCILeech (alternatively copy the file M:\memory.pmem if you use my memprocfs program and then try to use the dump file in your C# program. Does it cause the same issue?

Yes I experienced the same issue I  am pretty sure I did this right after creating the dump with memproc and running from that I get the same issue.
![Screenshot_6](https://user-images.githubusercontent.com/47060964/195923245-498460da-c58f-436c-beaf-8c82ea0522d7.png)
![Screenshot_7](https://user-images.githubusercontent.com/47060964/195923270-cd9e9f65-7ea6-42db-bf3f-39e4aea33413.png)
![Screenshot_8](https://user-images.githubusercontent.com/47060964/195923283-170dc11c-6f1a-43d6-9e5d-65506b919975.png)
Sorry for the wait I took a nap.

**Comment by ufrisk** [comment]
This is really good news. Then we have a way of locating this.

If you haven't already done it can you please check that you get the same error using the latest download from https://github.com/ufrisk/MemProcFS/releases/tag/v5.1    (at the bare minimum you'd need to make sure the vmm.dll and leechcore.dll in your installation are the most recent, copy from the download).

If the error persists, are you able to share the memory dump with me? zip it, upload it somewhere and send me the link to pcileech@frizk.net or if you shoot med a DM on Twitter.

**Comment by MystifiedSky** [comment]
> This is really good news. Then we have a way of locating this.
> 
> If you haven't already done it can you please check that you get the same error using the latest download from https://github.com/ufrisk/MemProcFS/releases/tag/v5.1 (at the bare minimum you'd need to make sure the vmm.dll and leechcore.dll in your installation are the most recent, copy from the download).
> 
> If the error persists, are you able to share the memory dump with me? zip it, upload it somewhere and send me the link to [pcileech@frizk.net](mailto:pcileech@frizk.net) or if you shoot med a DM on Twitter.

Son of a b**ch I must of been using a old copy / corrupt copy after replacing those two it is working fine now..... I appreciate the amazing support and making everything so understandable!

**Comment by ufrisk** [comment]
Awesome that you managed to fix it. Yeah best is probably to let the vmm.dll end leechcore.dll follow along the vmmsharp.cs file you're using.

Best wishes with your project. If you run into anything please let me know, or if you'd like for more features.

If you find my project useful in the end please consider sponsoring my project. It comes for as little as $2/month. Thank You 💖
