### ISSUE TITLE
ASM2362 and ASM2364 support?

### ISSUE THREAD

**Issue by RoganDawes** [ufrisk/LeechCore#33]
Not expecting anything, but wondering whether there is a chance of supporting the above USB-NVMe controllers? There is a project reversing the interface to them here: https://github.com/cyrozap/usb-to-pcie-re

The hardware seems to have great potential in terms of speed, if only the actual programming of it can be figured out. Although there was mention that this might only be able to operate as a PCIe root, but not as a device?

**Comment by RoganDawes** [comment]
Thanks for the quick response. Would be very interesting, both from a speed and cost/accessibility perspective. Might just need a passive M.2 to USB-C/M.2 to PCIe/M.2 to USB cable to PCIe riser adapter, if the hardware is flexible enough to be programmed as a device.

**Comment by cyrozap** [comment]
As far as I'm aware, ASM236x devices only support root complex operation--if there's a way to configure them as endpoint devices, I haven't found out how to do that yet. That said, these devices do support sending arbitrary TLPs (I've confirmed that both PCI config space and memory accesses work, with a hardware limit of one dword read or written per request TLP), and they have (small, 2-4 kB) internal buffers that can be DMA'd to/from by PCIe endpoints on the bus. I'm not yet certain if the DMA addresses of those internal buffers are configurable, though, so it remains to be seen whether these chips would be useful for PCIe MitM.

Also, I want to be very clear that I'm still very early in the process of reverse engineering these chips. I still don't really know how the USB side of the chip works, or how the internal DMA engine works (for transmitting the contents of the PCIe-accessible buffers over USB and receiving data from the USB host into those buffers), or how their interrupts are routed, and it will be necessary to understand how all of these systems work before it will be possible to write a FOSS custom firmware that can perform arbitrary PCIe reads and writes at rates faster than ~4 kB/s (what the current Python code interacting with the stock firmware is capable of).
