### ISSUE TITLE
Add support for libftd3xx on Linux

### ISSUE THREAD

**Issue by dank** [ufrisk/LeechCore#34]
FTDI released a [D3XX Linux driver](https://ftdichip.com/drivers/d3xx-drivers/). This might increase performance on Linux with async reads/writes.

 It doesn't look like this driver is a direct replacement for `leechcore_ft601_driver_linux`. The function signature for `FT_ReadPipe` and `FT_WritePipe` differ and it includes a dedicated function for async operation (`FT_ReadPipeAsync`).

**Comment by dank** [comment]
This library actually seems to work as a drop in replacement, albeit without the async features. Although I was getting segfaults when I tried before... which could be a bug with the driver, your mileage may vary.

**Comment by ufrisk** [comment]
Thanks, this is something I should be looking into. I'll put it on my list, I have a few other things that I'd have planned on finishing up first, but hopefully this won't be too long before I'm looking into it.

**Comment by ufrisk** [comment]
I've added 100% performance gain to the open source driver. I don't think there is much need for the FTDIchip proprietary driver after this addition.

If you find any issues with the new implementation let me know.

I'm closing this issue.
