### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by alukaduo09** [ufrisk/LeechCore#37]
Hello. I have a problem now. How do I get permission to run processes that are currently running?

**Comment by ufrisk** [comment]
I don't understand this question. If you have questions to ask you may join the [Discord server](https://discord.gg/BCmfBhDPXX) and ask questions there also.

**Comment by alukaduo09** [comment]
For example:  administrator,  system , Guest 
I only need to obtain this information about the process.

**Comment by alukaduo09** [comment]
> I don't understand this question. If you have questions to ask you may join the [Discord server](https://discord.gg/BCmfBhDPXX) and ask questions there also.

For example: administrator, system , Guest
I only need to obtain this information about the process.

**Comment by ufrisk** [comment]
This is available in the token sub-directory: https://github.com/ufrisk/MemProcFS/wiki/FS_Process_Token

**Comment by alukaduo09** [comment]
> 这在令牌子目录中可用：https://github.com/ufrisk/MemProcFS/wiki/FS_Process_Token

Thank you so much, that's what I need
