### ISSUE TITLE
Regarding the Thunderbolt 4 interface issue

### ISSUE THREAD

**Issue by scl1584547293** [ufrisk/LeechCore#42]
Does LeechCore support reading physical memory data from Thunderbolt 4 interface？

**Comment by ufrisk** [comment]
Thunderbolt DMA is just ordinary PCIe DMA. You may have to disable some default security settings in BIOS to make it work tho.

And the enclosure/adapter have to support it. Many of the nvme enclosures do not. Some do though.

CaptainDMA have an M2 device with a Thunderbolt enclosure that will work

**Comment by scl1584547293** [comment]
My DMA hardware is plugged into my laptop using Thunderbolt 4 interface. When using pcileech to read physical memory, the data read is always empty?

**Comment by ufrisk** [comment]
You'd most likely have to adjust security settings for DMA to work over Thunderbolt. There are some info for it:

https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt
https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_DMA_Not_Working

If that doesn't work it's probably a better idea to ask around in the Discord for guidance than here at Github. (The issues are more for bugs etc. than asking questions).
