### ISSUE TITLE
Dead Link on WinPMem Wiki Page

### ISSUE THREAD

**Issue by GoToHetch** [ufrisk/LeechCore#44]
The WinPmem GitHub was restructured 3 months ago (https://github.com/Velocidex/WinPmem/commit/59889475fd6341961caf9f6b75f7348b691109f8). As a result, the download link to the driver file on the [wiki page](https://github.com/ufrisk/LeechCore/wiki/Device_WinPMEM#requirements) is dead. The new download URL is https://github.com/Velocidex/WinPmem/raw/master/src/binaries/winpmem_x64.sys

**Comment by ufrisk** [comment]
Many thanks for letting me know about this. It's hard for me to always be updated and tracking changes like this. But the issue is now resolved. Thank You :)
