### ISSUE TITLE
Cannot read memory when device and vendor ID set as 0xFFFF

### ISSUE THREAD

**Issue by 1ZU4L** [ufrisk/LeechCore#8]
Hi,

I have a problem. Pcileech and memprocfs can't read memory when I set the device and vendor ID as 0xffff. How can I fix this?

**Comment by ufrisk** [comment]
I have not looked into it in detail. You should however able to read memory below 4GB when running that configuration. I know it's usually not enough since computers usually have more memory than that. But I haven't been looking into it enough to say whether it would be possible or not to read memory above 4GB as well. Please let me know if you find something out :)

**Comment by 1ZU4L** [comment]
Old 32-bit devices can read more than 4GB with driver support. Why do you think it cannot read more than 4GB?

**Comment by ufrisk** [comment]
as you mention with driver support yes. But I've only done some brief tests with regards to this, but maybe I wasn't looking at it closely enough, if you're able to read more than 4GB without driver please let me know.

**Comment by 1ZU4L** [comment]
So, is it not possible for leechcore or pcileech to emulate a driver? In the end, PCIe devices read memory without a driver thanks to your project.
I was able to probe the entire 16 GB of memory by changing the following line in leechcore:
`ctxDeviceMain->cfg.paMaxNative`
https://github.com/ufrisk/LeechCore/blob/0c1aa94be8ad32ece13fb2532a4cfccb9254b694/leechcore/leechcore.c#L532
So, if probing works after a change in the code, reading should work as well. Am I wrong?

**Comment by ufrisk** [comment]
I tested this again, by only changing device/vendor id and it works fine without changing anything else including your code line. Last time I looked into this I think I set some other values as well so I think that was the reason why I only was able to read 4GB.

**Comment by ysovv** [comment]
@1ZU4L @ufrisk which hard coded value did you test with?

**Comment by ufrisk** [comment]
This should now be fixed in the new release.

It should now be auto-detected whether the tiny algorithm will be required or not to read memory unless a user-defined max memory is specified, which in case you may need to specify algo=2 (tiny) as `fpga://algo=2`
