### ISSUE TITLE
Version 1.6: "Failed to connect to the device."

### ISSUE THREAD

**Issue by 1ZU4L** [ufrisk/LeechCore#9]
Version 1.5 works fine on all pcileech versions but when I replace version 1.5 files with version 1.6 files, it fails to connect to the device regardless of pcileech version I use.

**Comment by ufrisk** [comment]
You need to use the most recent version of the FTD3XX.dll for it to work. I changed the requirements betwen v1.5 and v1.6.

**Comment by 1ZU4L** [comment]
I downloaded the version 1.3.0.2 both as executable installer and as .inf format. Neither of them worked. Still can't read or probe with v1.6. Please take a look at the screenshot below:
![ftdi](https://user-images.githubusercontent.com/60180969/72944196-8847d400-3d78-11ea-9e17-e61e129ae81c.PNG)

**Comment by ufrisk** [comment]
Yes, you do need to download the latest version of <b>`FTD3XX.dll`</b> - not install the driver itself which is installed by Windows automatically anyway. 

![image](https://user-images.githubusercontent.com/18221464/72963794-77b74e00-3db8-11ea-9eb6-a9191ead8a00.png)

place the 64-bit version of `FTD3XX.dll` in the same directory as pcileech.exe

**Comment by 1ZU4L** [comment]
Thank very much. Using FTD3XX.dll version 1.3.0.2 solved the issue.
